### ISSUE TITLE
[Event]: Novel Design Strategies for Effective Next-Generation Nuclear Localization Signal (NLS)-Therapeutics

### ISSUE THREAD

**Issue by VIVIANCREATIVE** [BioconductorBoards/CABWorkingGroups#35]
### Type

webinar

### Description

It involves description the need to develop a more precise method in investigating nuclear transport dynamics of NLS-therapeutics. Moreover, Dr. Leyton will also present a de novo approach for generating novel NLSs with an atypical zero net-charge and evaluating various strategies to determine the worth for integration into NLS-therapeutics development.

### Location

online

### Website

https://www.creative-biolabs.com/adc/webinar-novel-design-strategies-for-effective-next-generation-nuclear-localization-signal-nls-therapeutics.htm

### Start date and time

10 AM EST, January 21, 2022

### End date and time

11 AM EST, January 21, 2022

### Time zone

EST

### Contact Details

marketing@creative-biolabs.com

### Registration details (if applicable)

Register link: https://www.creative-biolabs.com/adc/webinar-novel-design-strategies-for-effective-next-generation-nuclear-localization-signal-nls-therapeutics.htm

### Sponsor or Organization

Sponsor or organization

### Checklist

- [ ] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
Hi @VIVIANCREATIVE ,
Could you tell me how this webinar seems to have something to do with Bioconductor?
I checked [the website](https://www.creative-biolabs.com/adc/webinar-novel-design-strategies-for-effective-next-generation-nuclear-localization-signal-nls-therapeutics.htm) but couldn't find the relevance.

**Comment by VIVIANCREATIVE** [comment]
Hi Kozo,

Thanks for getting back to me!

I just googled and found that your website accepts such kinds of
event submissions related to biotech, and was wondering if your
scientists would be interested.

Sorry for the inconvenience if this is something you are not into it.

Thanks!

**Comment by kozo2** [comment]
@VIVIANCREATIVE It's me who should be apologizing.
I think the problem is that I didn't explicitly ask for a relationship with Bioconductor in the form.
Thanks to you, I got a chance to improve it.
I hope you will get involved with Bioconductor on another occasion.
Thanks!
