### ISSUE TITLE
Multi-omic data science with R/Bioconductor: Oulu summer school

### ISSUE THREAD

**Issue by antagomir** [BioconductorBoards/CABWorkingGroups#37]
### Type

Practical course with lectures.

### Description

The course focuses on R/Bioconductor for multi-omic data integration and analysis using the state-of-the-art data containers including MultiAssayExperiment and TreeSummarizedExepriment. We will use demonstration data sets from microbiome studies but the participants will also have a chance to experiment with their own data, if they wish.

### Location

University of Oulu, Finland

### Website

https://microbiome.github.io/course_2022_oulu

### Start date and time

June 20, 2022

### End date and time

June 23, 2022

### Time zone

EEST (Easter European Time / Helsinki)

### Contact Details

jenni.hekkala@oulu.fi

### Registration details (if applicable)

See the event homepage for registration details.

### Sponsor or Organization

- Health and Biosciences Doctoral Programme University of Oulu Graduate School
- Cancer & Translational Medicine Research Unit, University of Oulu
- Department of Computing, University of Turku, Finland
- Finnish IT Center for Science (CSC)
- ML4microbiome COST Action network

### Comment field

Similar courses will be available also later. Follow microbiome.github.io for more information.

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@antagomir I added your event to the Bioconductor event calendar. https://bioconductor.org/help/events/
I would appreciate it if you could check if it's okay.
If you have any problems, please feel free to reply.

In addition to the above,
I have sent an update request to the official website as below, but it has not been updated yet.

https://github.com/Bioconductor/bioconductor.org/pull/159
I'll contact you again when it's updated, but I'll close this issue for now.

**Comment by antagomir** [comment]
Thanks! Looks great. I am not sure if the time zone is correct, in my view
it says "02:00 – 10:00". The time is 9am-5pm Finnish time (EEST) daily. But
I am also not sure if this detail matters as it is just normal office hours
in Finland on those days.

Leo

**Comment by kozo2** [comment]
Hi @antagomir 
Thank you for the information.
It seems that the Bioconductor Event Calendar's time zone is fixed in New York.
I'll check if it can be changed to different time zones.

By the way,
your event is now displayed not only on the calendar but also on [the website](https://bioconductor.org/).

Thank you for sharing your event information.
Kozo
