### ISSUE TITLE
 Developing R/Bioconductor packages for genomics 

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#38]
### Type

5-day online Course

### Description

This course aims at making Bioconductor package development within one’s reach. It is specifically designed for biologists and newer bioinformaticians who may find themselves using R/Bioconductor packages and who wish to expand their programmatic toolkit.

Overall, this course will help the attendees gain accurate insights into the fundamental notions required for proper R/Bioconductor package development. We will cover key theory concepts about package development and the Bioconductor ecosystem, supported by a range of demonstrations and exercises, to get a complete understanding of all the steps of package development.

Throughout this workshop, we will emphasise on the best practices for developing a package embedded in the R/Bioconductor ecosystem.  The course is structured in modules over five days. Each day will contain a mix of formal lectures, demonstrations, and hands-on exercises.

 

    Formal lectures will cover the key theory required to understand the principles of R/Bioconductor package development (~2h).
    Following these lectures, practical examples will be shown to illustrate how to translate the acquired knowledge into a real-life R/Bioconductor package. At this stage, trainees will get acquainted with the state-of-the-art Bioconductor ecosystem as well as the best coding practices in bioinformatics.
     During the rest of the daily sessions, trainees will work by themselves, following guided exercises to practice their package development skills. Hints and solutions are provided for each exercise. The exercises will mainly focus on specific concepts introduced earlier that day.

 

 Office hours will take place during the last hour of the exercises. An instructor will be available to answer individual questions related to daily exercises.

 

 A Slack channel will also be available so that Q&A is available for everybody.

  

### Location

online

### Website

https://www.physalia-courses.org/courses-workshops/r-packages/

### Start date and time

October 24th

### End date and time

October 28th

### Time zone

Central European time 2-8 pm 

### Contact Details

Info@physalia-courses.org

### Registration details (if applicable)

Registration details: https://www.physalia-courses.org/courses-workshops/r-packages/

### Sponsor or Organization

Physalia-courses: https://www.physalia-courses.org/

### Comment field

 The material is suitable both for experimentalists who want to learn more about R/Bioconductor ecosystem as well as computational biologists who want to expand their set of coding skills. However, the course will be most beneficial to those who have already been familiarized with the R environment.

  

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@Physalia86 Thank you for sharing the event information!
I added the event information to [the Bioconductor event calendar](https://bioconductor.org/help/events/) (in the Google Calendar part).
Updating "Upcoming" of https://bioconductor.org/help/events/ will be done when https://github.com/Bioconductor/bioconductor.org/pull/161 is merged.

**Comment by Physalia86** [comment]
Thanks so much Kozo!
 
Best regards,
Carlo
 
 
-----Original Message-----

**Comment by kozo2** [comment]
@Physalia86 Your event information has also been added to "Events" in https://bioconductor.org/ and "Upcoming" in https://bioconductor.org/help/events/ . I close this issue.
Thank you for sharing the event information!
