### ISSUE TITLE
[Event]: Introduction to genomic data analysis with R and Bioconductor

### ISSUE THREAD

**Issue by csoneson** [BioconductorBoards/CABWorkingGroups#39]
### Type

workshop

### Description

The Carpentries workshop on Introduction to R, with a view towards omics data. 

### Location

Heidelberg

### Website

https://bioconductor.github.io/2022-09-12-BiocIntro-Heidelberg/

### Start date and time

September 12, 9:00

### End date and time

September 13, 17:00

### Time zone

CEST

### Registration details (if applicable)

Registration details

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@csoneson 
Thank you for contacting us.
I added your event to [the Bioconductor Events Google Calendar](http://bioconductor.org/help/events/).
Addition to http://bioconductor.org is in the process of https://github.com/Bioconductor/bioconductor.org/pull/168 .

**Comment by kozo2** [comment]
@csoneson This event is now listed not only on the calendar but also the http://bioconductor.org/.
I close this issue. 
It would be great if you could post the event report on the community blog after the event!
