### ISSUE TITLE
Viral RNA Modifications and Implications for Novel Therapeutics

### ISSUE THREAD

**Issue by krystalbeily** [BioconductorBoards/CABWorkingGroups#43]
### Type

webinar

### Description

This webinar will cover the role of RNA modifications in viral replication, specifically the influenza A virus, and how it might inform the design of both novel antivirals and mRNA-based therapeutics.

### Location

Virtual

### Website

https://www.bocsci.com/webinar-viral-rna-modifications-and-implications-for-novel-therapeutics.html

### Start date and time

September 19th, 11:00 EDT | September 19th, 16:00 BST

### End date and time

September 19th, 12:30 EDT | September 19th, 17:30 BST

### Time zone

Eastern Standard Time

### Contact Details

account@bocsci.com

### Registration details (if applicable)

Please register at https://www.bocsci.com/webinar-viral-rna-modifications-and-implications-for-novel-therapeutics.html

### Sponsor or Organization

Organized by BOC Sciences

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@krystalbeily I'm really sorry. I'm late in catching this issue.
Please allow me to reply after the event has already taken place.
I looked at the event's website, but I couldn't read the connection between the event and Bioconductor.
Are (/Were) any Bioconductor software be used at this event?

**Comment by kozo2** [comment]
I close this issue since the event date has already passed.
We would love to hear from you if you have any [Bioconductor-related] events.
