### ISSUE TITLE
"virtual" remark may need modification

### ISSUE THREAD

**Issue by vjcitn** [BioconductorBoards/CABWorkingGroups#44]
The [form page for events](https://github.com/BioconductorBoards/CABWorkingGroups/issues/new?assignees=kozo2&labels=event%2Ccalendar&template=EVENT-CALENDAR.yml&title=%5BEvent%5D%3A+REPLACE+ME+WITH+YOUR+EVENT+TITLE)
includes the remark `(As of June 2021, "events" are assumed to be "virtual events" only.)`

Do we need that?

**Comment by lshep** [comment]
No; I don't think this is necessary anymore

**Comment by kozo2** [comment]
@vjcitn @lshep Thanks for letting me know it.
I removed the remark.
https://github.com/BioconductorBoards/CABWorkingGroups/commit/b72c5b4d8cfeccf35d5ffc42bb0bda6b2d999a45
