### ISSUE TITLE
[Event]: Hacktoberfest: Contributing to The Carpentries lesson about the Bioconductor project

### ISSUE THREAD

**Issue by mblue9** [BioconductorBoards/CABWorkingGroups#45]
### Type

meetup

### Description

In this meetup, we will describe how to contribute to [“The Bioconductor project” lesson](https://carpentries-incubator.github.io/bioc-project/) in The Carpentries incubator.
This is a [Hacktoberfest 2022](https://hacktoberfest.com/ ) edition of the Bioconductor community meetup.
Pull requests to the GitHub repository for the lesson merged during October 2022 count toward Hacktoberfest 2022 progress, leading to rewards such as stickers, t-shirts, or a tree planted in your name.

### Location

Online

### Website

https://www.meetup.com/boston-r-bioconductor-for-genomics/events/289042169/

### Start date and time

4pm

### End date and time

5pm

### Time zone

BST

### Contact Details

maria.doyle@ul.ie

### Registration details (if applicable)

Registration details

### Sponsor or Organization

Bioconductor

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@mblue9 Thank you for sharing the information!
I added the event to [the "Bioconductor Events" Google Calendar](https://www.bioconductor.org/help/events/).
The website (bioconductor.org) itself (HTML other than embedded Google Calendar) will be updated later.

**Comment by kozo2** [comment]
The update request of the bioconductor.org was sent like https://github.com/Bioconductor/bioconductor.org/pull/179
.
