### ISSUE TITLE
[Event]: Hacktoberfest: Let the community know about your activities on the biocblog

### ISSUE THREAD

**Issue by mblue9** [BioconductorBoards/CABWorkingGroups#46]
### Type

meetup

### Description

In this meetup, we are looking for blog contributions from community members.
This is the Hacktoberfest edition of Bioconductor community meetup.
[Hacktoberfest](https://hacktoberfest.com) is an open source project festival that invites GitHub pull request from everyone. 
The blog posts are made by sending pull requests to https://github.com/bioconductor/biocblog .
You can use any language for your blog posts.

### Location

Online

### Website

https://www.meetup.com/bioconductor-community-in-asia/events/288949678/

### Start date and time

3pm

### End date and time

5pm

### Time zone

JST

### Registration details (if applicable)

Registration details

### Sponsor or Organization

Bioconductor

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@mblue9 Thank you for sharing the information!
I added the event to [the "Bioconductor Events" Google Calendar](https://www.bioconductor.org/help/events/).
The website (bioconductor.org) itself (HTML other than embedded Google Calendar) will be updated later.

**Comment by kozo2** [comment]
The update request of the bioconductor.org was sent like https://github.com/Bioconductor/bioconductor.org/pull/180.
