### ISSUE TITLE
FLOW CYTOMETRY ANALYSIS WITH R/BIOCONDUCTOR course

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#47]
### Type

course

### Description

COURSE OVERVIEW
This course introduces what flow cytometry is and why we use it to analyze cell population composition in biological samples. We will learn about best practices for how to analyze flow cytometry data using R/Bioconductor. Said practices include: preprocessing of the data (compensation, transformation, and quality control), multi-dimensional cell population identification via clustering, and visualizing the results in 2D. These tools can be applied to all types of cytometry including flow, mass, and spectral.

TARGET AUDIENCE AND ASSUMED BACKGROUND
This course is created for anyone interested in analyzing biological samples with single-cell flow cytometry. Background in flow cytometry and R/Bioconductor is not necessary as we will go over a short introduction to them. However, experience with programming will help greatl

LEARNING OUTCOMES
1- Understand the flow cytometry machinery and its analytical purpose.

2- Be able to set up the infrastructure for and write basic data analytic scripts in R.

3- Describe and execute each step in the flow cytometry data analytics pipeline in R/Bioconductor.

4- Be comfortable with interpreting and eliciting conclusions from the results of the flow cytometry data analytics pipeline.

### Location

online

### Website

https://www.physalia-courses.org/courses-workshops/flow-cytometry/

### Start date and time

January 16th-4-8 pm Berlin time

### End date and time

January 19th--4-8 pm Berlin time

### Time zone

Berlin time

### Contact Details

info@physalia-courses.org

### Registration details (if applicable)

Registration details

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@Physalia86 Thank you for sharing the information!
I added your event to [the "Bioconductor Events" Google Calendar](https://www.bioconductor.org/help/events/).
The website (bioconductor.org) itself (HTML other than embedded Google Calendar) will be updated later.

**Comment by kozo2** [comment]
@Physalia86 Sorry for the late reply.
The event is already on the https://bioconductor.org .
Thank you for sharing your event with us.

**Comment by Physalia86** [comment]
Hi Kozo,
 
many thanks for this.
 
Happy New Year,
Carlo
 
 
-----Original Message-----
