### ISSUE TITLE
[Event]: REPLACE ME WITH YOUR EVENT NAME

### ISSUE THREAD

**Issue by bnaras** [BioconductorBoards/CABWorkingGroups#48]
### Type

R workshop

### Description

Two half-day workshops:  (a) Visualization and Graphics and (b) Advanced R

### Location

Indian Institute of Science, Bengaluru, India.

### Website

https://r-iisa2022.rbind.io

### Start date and time

December 30, 2022, 9am local time

### End date and time

December 30, 2022, 5:30pm local time.

### Time zone

India Standard Time

### Contact Details

r2022iisa@gmail.com

### Registration details (if applicable)

See website

### Sponsor or Organization

[Rstudio/Posit](https://posit.co) and [R Consortium](https://www.r-consortium.org/).

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@bnaras I'm sorry, I missed this event PR.
I couldn't find any connection between this event and Bioconductor.
I close this issue.
If you have any events in the future, please feel free to contact us.
