### ISSUE TITLE
 Gene Set Enrichment Analysis in R/Bioconductor 

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#49]
### Type

workshop

### Description

 Gene set enrichment analysis (GSEA) is a basic method for biological data analysis. It is used to associate biological functions to a list of genes of interest, which is to explain the results from a biology point of view. In this course, we will teach the use of popular GSEA tools, both for online-based tools and those implemented as R packages. We will give a detailed introduction to a variety of methods of GSEA analysis, including overrepresentation analysis, univariate methods, multivariate methods, as well as extensions of GSEA analysis, such as network-based GSEA, and single-sample GSEA. Finally, you will also learn downstream processing of GSEA results, including efficiently visualizing the massive GSEA results, clustering, and simplifying GSEA results via various methods.
In the course, we will cover some other topics that are tightly related to GSEA analysis, such as multiple hypothesis testing. You will also learn how to implement GSEA methods completely from scratch in R.

Instructor: Dr. Zuguang Gu (https://jokergoo.github.io/; German Cancer Research Center (DKFZ)) 

### Location

online

### Website

https://www.physalia-courses.org/courses-workshops/gse-in-r/

### Start date and time

30th of January 2023 (2-8 PM)

### End date and time

2nd of February 2023 (2-8 PM)

### Time zone

Central European Time Zone

### Contact Details

Info@physalia-courses.org

### Registration details (if applicable)

Registration details

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@Physalia86 Thank you for sharing your event schedule with us! (I'm sorry for the late reply...)
I added the schedule to the Bioconductor evnet calendar.
https://bioconductor.org/help/events/
I also sent a pull request to update https://bioconductor.org/ in https://github.com/Bioconductor/bioconductor.org/pull/193
I close this issue once, but I will let you know as soon as the website is updated.
