### ISSUE TITLE
Bioconductor teaching committee meeting

### ISSUE THREAD

**Issue by csoneson** [BioconductorBoards/CABWorkingGroups#50]
### Type

community discussion

### Description

Monthly meeting of the Bioconductor teaching committee

### Location

[event location](https://meet.jit.si/BioconductorTeaching)

### Website

https://bioconductor.org/help/education-training/

### Start date and time

Generally, the second Monday of each month at 3pm Central European time. Occasionally the meeting can happen at another time, any changes are announced via the google group linked from the website above. The next meetings are: 
Monday, January 16 (exceptionally on the third Monday)
Monday, February 13

### End date and time

4pm Central European time, same days as above

### Time zone

Central European time (CEST in summer, CET in winter)

### Registration details (if applicable)

No registration necessary

### Sponsor or Organization

Sponsor or organization

### Comment field

Generally, the meetings happen on the second Monday of each month at 3pm Central European time. Occasionally the meeting can happen at another time, any changes are announced via the google group linked from the website above.

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@csoneson Thank you for sharing your event schedule with us! (I'm sorry for the late reply...)
I added the schedule to the Bioconductor evnet calendar.
https://bioconductor.org/help/events/
I also sent a pull request to update https://bioconductor.org/ in https://github.com/Bioconductor/bioconductor.org/pull/192
I close this issue once, but I will let you know as soon as the website is updated.

**Comment by csoneson** [comment]
Thanks @kozo2! Looks great.

**Comment by csoneson** [comment]
Hi @kozo2 - would it be possible to update this event in the calendar to be at 15:00 CEST from April onwards (it's entered in CET, which is fine until this Sunday, but after that will be incorrect)? 
Also, if you are anyway editing - the April meeting will take place on April 3 (15:00 CEST) instead of April 10, as the latter is Easter Monday. Only this occurrence is affected.
Thanks!

**Comment by kozo2** [comment]
@csoneson I have made a change to set the time of the event an hour earlier than in April 3, and then May onwards.
Is https://bioconductor.org/help/events/ what you meant?

**Comment by csoneson** [comment]
Thanks so much @kozo2 - this looks right to me!

**Comment by csoneson** [comment]
Hi @kozo2 - I was wondering if this event could be updated again to reflect that we have now changed back to winter time. To be precise, the meeting should now be at 3pm CET (or Central European Standard Time), i.e., one hour later than it's currently scheduled. Thanks!
