### ISSUE TITLE
Revolutionizing Next-Generation Sequencing (5th edition)

### ISSUE THREAD

**Issue by VIBConferences** [BioconductorBoards/CABWorkingGroups#51]
### Type

Conference

### Description

Next generation sequencing has been and is still revolutionizing discoveries across life sciences. While established sequencing technologies are now fully embedded in the clinic and diagnostic settings, novel technological advancements spur the next revolution in sequencing technologies. These will open new avenues for research and enable new genomics insights not possible before. This conference aims to bring together experts in both established and novel sequencing technologies along with top scientists in the field.

Over the past decade, technological advances that enable the characterization of single cells at the molecular level rather than in bulk tissues have led to significant breakthrough discoveries with revolutionary insights in diseases, such as cancer, inflammatory and neurodegenerative diseases. Therefore, specific focus of this conference will be on advances in single cell sequencing, ranging from transcriptomics, genomics, proteomics to combined multi-omics analysis at the single cell level. On top, with spatial context of cells becoming increasingly important to unravel cell functioning and behavior, a dedicated session will focus on technological advancements in spatial sequencing and breakthrough scientific discoveries that these have enabled.

This exciting conference puts together an excellent program including renowned leaders in the field that will cover the following topics:

Emerging sequencing platforms
New applications of long read sequencing technologies
Computational genomics & data analysis
Outbreak sequencing & population-scale
Single cell sequencing
Spatial technologies

In addition to a great scientific and technology program, the conference will provide many opportunities to network during the breaks, poster sessions and much more!

### Location

De Bijloke
Bijlokekaai 7
9000 Gent

### Website

https://www.vibconferences.be/events/revolutionizing-next-generation-sequencing-5th-edition

### Start date and time

27/03/2023 08:30 

### End date and time

28/03/2023 18:30

### Time zone

Central European Standard Time

### Contact Details

conferences@vib.be

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
Hello @VIBConferences .
Thank you for sharing your event information.
But I couldn't find any Bioconductor information in https://www.vibconferences.be/events/revolutionizing-next-generation-sequencing-5th-edition .
Could you tell me how this event is likely to relate to the Bioconductor community?

**Comment by kozo2** [comment]
@VIBConferences I'm sorry, I close this issue.
I couldn't find the relevance between this event and Bioconductor.
If you have any other PR, please feel free to contact us.
