### ISSUE TITLE
Webinar: Naturally Occurring Sensitive Nucleic Acids, Applications and Chemical Synthesis

### ISSUE THREAD

**Issue by MarinaBarrow** [BioconductorBoards/CABWorkingGroups#52]
### Type

webinar

### Description

March 9th, 2023 14:00 EST
Session Description
Nucleic acids including DNA and RNA contain over 150 noncanonical nucleosides. Among these epigenetically modified nucleosides, many are sensitive to conditions used by the existing DNA/RNA synthesis technologies. Therefore, nucleic acids containing sensitive modified nucleosides are currently inaccessible via synthetic chemistry or highly challenging.

In this presentation, Dr. Shiyue Fang will showcase experimental examples of sensitive nucleosides, including their biological roles and relationships to clinical applications, challenges related to nucleic acids synthesis containing sensitive nucleosides, and the current status of the Dim-Dmoc method developed by his research group at the Michigan Technological University that overcomes related obstacles. In addition, Dr. Fang will also share personal opinions regarding the potential applications of sensitive nucleic acids accessible by the Dim-Dmoc method.

Highlights of the presentation
1. Diverse structures of sensitive nucleosides
2. Insights on applications of sensitive nucleic acids
3. Dim-Dmoc methods for sensitive nucleic acid synthesis

### Location

Online

### Website

https://rna.bocsci.com/support/webinar-naturally-occurring-sensitive-nucleic-acids-applications-and-chemical-synthesis.html

### Start date and time

March 9th, 2023 14:00 

### End date and time

March 9th, 2023 17:00 

### Time zone

EST

### Contact Details

account@bocsci.com

### Registration details (if applicable)

[Registration details](https://rna.bocsci.com/support/webinar-naturally-occurring-sensitive-nucleic-acids-applications-and-chemical-synthesis.html)

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
Hello @MarinaBarrow .
Thank you for sharing your event information.
But I couldn't find any Bioconductor information in https://rna.bocsci.com/support/webinar-naturally-occurring-sensitive-nucleic-acids-applications-and-chemical-synthesis.html .
Could you tell me how this event is likely to relate to the Bioconductor community?

**Comment by kozo2** [comment]
@MarinaBarrow I'm sorry, I close this issue.
I couldn't find the relevance between this event and Bioconductor.
If you have any other PR, please feel free to contact us.
