### ISSUE TITLE
Single-Cell RNAseq with R/Bioconductor

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#53]
### Type

Course

### Description

COURSE OVERVIEW
This course will introduce biologists and bioinformaticians to the field of single-cell RNA sequencing. We will cover a range of software and analysis workflows that extend over the spectrum from the best practices in the filtering scRNAseq data
to the downstream analysis of cell clusters and temporal ordering. This course will help the attendees gain accurate insights in pre-processing, analysis and interpretation of scRNAseq data.

We will start by introducing general concepts about single-cell RNA-sequencing. From there, we will then continue to describe the main analysis steps to go from raw sequencing data to processed and usable data. Finally, we will focus more specifically on the different analyses strategies to use in order to extract information from genomic datasets such as Hi-C, ATAC-seq or ChIP-seq.

Throughout the workshop, bash tools and R/Bioconductor packages will be used to analyse datasets and learn new approaches.
 
COURSE FORMAT
The course is structured in modules over five days. Each day will include formal lectures covering the key concepts required to understand scRNAseq analysis. The remainder of each day will consist in practical hands-on sessions focusing on analysis of scRNA-seq data. These sessions will involve a combination of both mirroring exercises with the instructor to demonstrate a skill, as well as applying these skills on your own to complete individual exercises.

During and after each exercise, interpretation of results will be discussed as a group.
 
TARGETED AUDIENCE & ASSUMED BACKGROUND
The course will be mostly beneficial to those who have, or will shortly have, scRNA-seq data ready to analyse.

The material is suitable both for experimentalists who want to learn more about data-analysis as well as computational biologists who want to learn about scRNASeq methods.

Examples demonstrated in this course can be applied to any experimental protocol or biological system.

The requirements for this course are:

Working knowledge of Unix / command line interface (managing files, running programs, reading manuals!). Basic bash commands (cd, ls, ...) and CLI usage will not be covered in this course. We advice attendees to not register if they lack fundamental experience in CLI.
Programming experience in R (writing a function, basic I/O operations, variable types, using packages). Bioconductor experience is a plus.
Familiarity with next-generation sequencing data and its analyses (using alignment and quantification tools for bulk sequencing data)
 
LEARNING OUTCOMES
At the end of this course, you should be able to:
Understand the pros/cons of different single-cell RNA-seq methods
Process and QC of scRNA-seq data
Normalize scRNA-seq data
Correct for batch effects
Visualise the data and applying dimensionality reduction
Perform cell clustering and annotation
Perform differential expression analysis
Infer pseudo-time and perform temporal differential expression

Throughout the course, we will also have a focus on reproducible research, documented content and interactive reports.
 
 

### Location

Online

### Website

https://www.physalia-courses.org/courses-workshops/course18/

### Start date and time

June 5th - 2-8 pm Berlin time zone

### End date and time

June, 9th - 2-8 pm Berlin time zone

### Time zone

Berlin time zone

### Contact Details

info@physalia-courses.org

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@Physalia86 Thank you for sharing the event information!
I added the event information to [the Bioconductor event calendar](https://bioconductor.org/help/events/) (in the Google Calendar part).
![image](https://user-images.githubusercontent.com/12192/221869057-f7c29d9a-dad6-4bd9-a0f0-67f8ac130cbb.png)

Updating "Upcoming" of https://bioconductor.org/help/events/ will be done when https://github.com/Bioconductor/bioconductor.org/pull/203 is merged.
