### ISSUE TITLE
Multi-omic data analysis with R/Bioconductor

### ISSUE THREAD

**Issue by antagomir** [BioconductorBoards/CABWorkingGroups#54]
### Type

Summer course

### Description

 This course provides an introduction to multi-omic data integration and analysis with R/Bioconductor. After the course you will know how to organize multiple data sources into a coherent framework, implement reproducible data science workflows, and approach common data analysis tasks by utilizing available documentation and R tools. The primary focus is on microbiome research but the covered data science methods are generally applicable and we will discuss links with other application domains such as transcriptomics, metabolomics, and single cell sequencing.

### Location

University of Oulu, Oulu, Finland

### Website

https://microbiome.github.io/course_2023_oulu/

### Start date and time

Monday, June 19 at 9am Finnish time

### End date and time

Wednesday, June 21 at 4pm Finnish time

### Time zone

EEST (Finland / Helsinki summer time)

### Contact Details

anna.kaisanlahti@oulu.fi

### Registration details (if applicable)

See the event website for registration details.

### Sponsor or Organization

The course is organized by [Health and Biosciences Doctoral Programme (HBS-DP)](https://www.oulu.fi/en/research/graduate-school/organisation-and-contact-information-uniogs/health-and-biosciences-doctoral-programme) University of Oulu Graduate School, Research Unit of Translational Medicine, University of Oulu. 

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@antagomir I'm sorry, I didn't reply to this issue.
This event has indeed been added to the Bioconductor event calendar (and the Previous event).
https://bioconductor.org/help/events/
Sorry for the late reply. I close this issue.
