### ISSUE TITLE
Network Analysis in Systems Biology with R/Bioconductor

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#56]
### Type

workshop

### Description

COURSE OVERVIEW
This course will introduce participants with the inference and analysis of biological networks from RNA-seq data using R and Bioconductor packages. The course will cover data structures for quantitative data and graphs, statistical methods for network inference, functional analyses of biological networks, and network comparison. At the end of the course, participants will be able to infer and analyze gene coexpression networks (GCNs) and gene regulatory networks (GRNs), compare networks, and integrate GCNs with genetic markers to prioritize candidate genes associated with traits.

TARGET AUDIENCE AND ASSUMED BACKGROUND
The course is targeted to researchers and students that would like to learn how to use R and Bioconductor to infer and analyze networks for systems biology projects. Familiarity with RNA-seq and core Bioconductor data structures (e.g., SummarizedExperiment and GRanges) is helpful, but not essential, as they will be covered during the course. Participants need to have a working knowledge of R (R syntax, commonly used functions, basic data structures such as data frames, vectors, matrices and their manipulation).

PROGRAM
Monday - 2-7 pm Berlin time zone

Inference and Analysis of Gene Co-expression Networks (GCNs)

Theory:
● Types of networks
● Topological properties of biological networks
● Representing data as graphs
● Bias correction in co-expression network inference

Practice:
● Quantitative data and the SummarizedExperiment class
● Preprocessing, normalization, and transformation of expression data
● Inference of co-expression networks
● Functional analyses of network modules
● Network visualization

Tuesday- 2-7 pm Berlin time zone

Network comparison

Theory:
● Parametric and non-parametric network comparison
● Cross-species network comparison

Practice:
● Identifying consensus modules
● Identification preserved modules between networks
● Functional analyses of differences and similarities between networks

Wednesday - 2-7 pm Berlin time zone

Network-based data integration for gene discovery

Theory:
● Introduction to genome-wide association studies
● Bottlenecks in SNP-to-gene mapping

Practice:
● The GRanges class
● SNP-to-gene mapping
● Prioritizing candidate genes associated with a phenotype

Thursday - 2-7 pm Berlin time zone

Inference and Analysis of Gene Regulatory Networks (GRNs)

Theory:
● An overview of GRN inference algorithms
● GRN inference through an ensemble of methods
● GRN analyses and applications

Practice:
● Inference of GRNs
● Functional analyses of GRNs
● GRN visualization

### Location

online

### Website

https://www.physalia-courses.org/courses-workshops/network-in-systems-biology/

### Start date and time

September 11th 2-7 pm 

### End date and time

September 14th 2-7 pm

### Time zone

CEST

### Contact Details

info@physalia-courses.org

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
Hi @Physalia86 , I’m sorry for the late reply.
I have added your event to https://bioconductor.org/help/events/ .
I would appreciate it if you could confirm that there are no problems with the addition.

**Comment by kozo2** [comment]
@Physalia86 
I sent a PR to update the "Upcoming" section in Bioconductor Events page (as well as the Google Calendar).
https://github.com/Bioconductor/bioconductor.org/pull/241

I will message you again as soon as the PR is merged.
