### ISSUE TITLE
FLOW CYTOMETRY ANALYSIS WITH R/BIOCONDUCTOR

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#59]
### Type

online course

### Description

This course introduces what flow cytometry is and why we use it to analyze cell population composition in biological samples. We will learn about best practices for how to analyze flow cytometry data using R/Bioconductor. Said practices include: preprocessing of the data (compensation, transformation, and quality control), multi-dimensional cell population identification via clustering, and visualizing the results in 2D. These tools can be applied to all types of cytometry including flow, mass, and spectral.

### Location

To foster international participation, this course will be held online

### Website

https://www.physalia-courses.org/courses-workshops/flow-cytometry/

### Start date and time

January 15th -4 PM Berlin time

### End date and time

January 18th - 8 PM Berlin time

### Time zone

CET

### Contact Details

info@physalia-courses.org

### Registration details (if applicable)

https://www.physalia-courses.org/courses-workshops/flow-cytometry/

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by kozo2** [comment]
@Physalia86 Thank you for getting in touch. And I apologize for the delayed response. I have added your event to the Bioconductor calendar.
- https://bioconductor.org/help/events/
- http://new.bioconductor.org/help/events/
I will also update the website. I will comment later with the link to the pull request for the website update.
