### ISSUE TITLE
Brain, Bacteria and Behaviour: understanding the gut-brain axis (RSS4.06)

### ISSUE THREAD

**Issue by ake123** [BioconductorBoards/CABWorkingGroups#60]
### Type

Course

### Description

This course discuss the following

- The (Systems) Biology of the Microbiota and the various routes of gut-brain communication

- The role of the Microbiota -Gut-Brain Axis in behaviour and mental health

- Key modifiers of the gut microbiome (nutrition, stress, age, gender and host genes)

- Current methodological approaches to analyse Microbiota -Gut-Brain Axis-based hypothesis (data collection, bacterial DNA extraction, bioinformatic and statistical tools)

- Practical sessions aimed to analyse 16s RNA-gene microbiome data and associating it with brain imaging data and cognitive tasks. 

### Location

Location
[Berchmanianum ](https://www.ru.nl/en/about-us/the-campus/buildings-and-spaces/berchmanianum)
Houtlaan 4
6525XZ Nijmegen

### Website

https://www.ru.nl/en/education/education-for-professionals/overview/brain-bacteria-and-behaviour-understanding-the-gut-brain-axis-rss406

### Start date and time

08 July 2024, 9 am

### End date and time

12 July 2024, 5 pm

### Time zone

CET

### Registration details (if applicable)

- Regular: €700
- Early Bird: €630 (application deadline* April 1st)

**Admission**
**Level of participant:** 

- Master
- PhD
- Postdoc
- Professional
**Admission requirements:**

- Basic understanding of statistics (regression) and a working understanding of research methods
- Prior experience with the statistical analysis program R (with regard to loading and organisaising data, and loading packages)
- Background in behavioral science/psychiatry including knowledge about neurobiology and anatomy of the brain is recommended
 If you are unfamiliar with the statistical analysis program R, you are required to go through online tutorials before the course (e.g. chapter 1-3 of this [tutorial](https://intro2r.com/ ). You may also choose one of the other Radboud Summer School courses on R. Furthermore, if you want to update your knowledge before the course, you can read the suggested reading materials that will be provided to you. 

**Admission documents:** 

- Motivation letter 
- CV

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by lshep** [comment]
Your event has been added; it should show on the event calendar and in event section of the website within the next 24 hours
