### ISSUE TITLE
R/Bioconductor for Mass Spectrometry and Proteomics

### ISSUE THREAD

**Issue by Physalia86** [BioconductorBoards/CABWorkingGroups#61]
### Type

Online Course

### Description

This course will introduce participants to the analysis and exploration of mass spectrometry (MS) based proteomics data using R and Bioconductor. The course will cover all levels of MS data, from raw data to identification and quantitation data, up to the statistical interpretation of a typical shotgun MS experiment and will focus on hands-on tutorials. At the end of this course, the participants will be able to manipulate MS data in R and use existing packages for their exploratory and statistical proteomics data analysis.

### Location

Online

### Website

https://www.physalia-courses.org/courses-workshops/course58/

### Start date and time

18th March

### End date and time

20th March

### Time zone

2-8 PM CET

### Contact Details

info@physalia-courses.org

### Registration details (if applicable)

ttps://www.physalia-courses.org/courses-workshops/course58/

### Sponsor or Organization

Sponsor or organization

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by lshep** [comment]
Your event has been added; it should show on the event calendar and in event section of the website within the next 24 hours
