### ISSUE TITLE
[Event]: Microbiome data science & multi-omics with R/Bioconductor 

### ISSUE THREAD

**Issue by TuomasBorman** [BioconductorBoards/CABWorkingGroups#63]
### Type

training course, workshop

### Description

University of Oulu training school, Dec 18-20, 2024 (Wed-Fri)

This intensive 3-day course provides an introduction to microbiome data science and multi-omic data integration with R/Bioconductor, a popular open source environment for scientific data analysis. The course is intended for MSc students, PhD candidates, postdocs, and researchers who wish to learn new data analytical skills. Academic students and researchers from Finland and abroad are welcome and encouraged to apply. 
  
Registration is free. The course is organized in a live format, and participants are expected to cover their own travel and accommodation. See the course homepage for registration instructions and travel & accommodation tips. The course has maximum capacity of 20 participants. Applications from local students, and applications submitted by November 11 will be given priority.  
 
The course is organized by Health and Biosciences Doctoral Programme (HBS-DP) University of Oulu Graduate School, Research Unit of Translational Medicine, University of Oulu and the Biocity Turku CompLifeSci research program. We thank the Finnish IT Center for Science (CSC) for supporting the course with cloud computing services. This is a Bioconductor course and it follows the best practices recommended by Software Carpentries. 
  
For more details on course content, registration, teachers, travel & accommodation tips and other practical information, see the course homepage (https://microbiome.github.io/course_2024_oulu/).

### Where is your event located?

University of Oulu, Oulu, Finland, December 18-20, 2024 (Wed-Fri). Not virtual.

### Website

https://microbiome.github.io/course_2024_oulu/

### Repeating or one-off events?

One-off

### If you selected "Repeating", select below. If you selected "One-off", skip this.

Repeat every ___ , Repeat on ___ , Ends on ___ / Ends after ___ occurrences

### If you selected "One-off" or your event repeats in a manner other than the Google Calendar support types above,

Dec 18, Dec 19, Dec 20

### Registration details (if applicable)

On website.

### Sponsor or Organization

On website.

### Checklist

- [X] This event has a Bioconductor focus or interest to Bioconductor users/developers.
- [X] The event organizer read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event has the Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
- [X] The event organizer have the shorter version (summary) of the CoC.

**Comment by TuomasBorman** [comment]
@kozo2 Any updates on this?

**Comment by kozo2** [comment]
Dear @TuomasBorman 

I sincerely apologize for missing your issue earlier. It was entirely my fault, and I deeply regret any inconvenience this may have caused.

To prevent this from happening again, I am currently working on improving our event management system.

Please allow me to add your event to the Bioconductor event log after the event has taken place.
I will get back to you when I can add that event log.

Please forgive my mistake this time.

**Comment by TuomasBorman** [comment]
Hello @kozo2!

No worries at all, the course went great!

-Tuomas
